version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - /dev/null:/var/www/html/index.php

      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/assets:/var/www/html/assets

      - ./docker/production/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./em-breve:/var/www/html/em-breve
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - mapasculturais
    links:
      - mapasculturais
  
  mapasculturais:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./.env:/.env
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/var/private-files
      - ./docker-data/saas-files:/var/www/var/saas-files
      - ./docker-data/sessions:/var/www/var/sessions
      - ./docker-data/logs:/var/www/var/logs

      - ./docker/common/config.d:/var/www/config/common.d
      - ./docker/production/config.d:/var/www/config/config.d
      - ./docker/common/lgpd-terms:/var/www/config/lgpd-terms
    links:
      - db
      - redis
      - sessions
    environment:
      - REDIS_CACHE=redis
      - SESSIONS_SAVE_PATH=tcp://sessions:6379

    depends_on:
      - db
      - redis
      - sessions

  redis:
    image: redis:6
    command: --maxmemory 1256Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
 
  sessions:
    image: redis:6
    command: --maxmemory 384Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - ./docker-data/sessions:/data

  db:
    image: postgis/postgis:16-master
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - ./docker-data/db-data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    environment:
      - MB_DB_TYPE=postgres 
      - MB_DB_DBNAME=metabase 
      - MB_DB_PORT=5432 
      - MB_DB_USER=metabase 
      - MB_DB_PASS=metabase 
      - MB_DB_HOST=db_metabase 
    ports:
      - "3000:3000"
  
    depends_on:
      - db_metabase
      
  db_metabase:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_DB=metabase
    volumes:
      # - ./compose/db/metabase.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
      - ./docker-data/metabase-data-20230417:/var/lib/postgresql/data
    

## Em ambiente de homologação pode ser uma boa ideia utilizar o mailhog para testar 
## o envio de emails e também prevenir que emails de tete sejam disparados acidentalmente 
## para os usuários no caso de o ambiente de homologação utilizar um banco de dados cópia
## de produção

  # mailhog: 
  #   image: mailhog/mailhog
  #   ports:
  #     - "8025:8025"