version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: compose/nginx/Dockerfile
    restart: always
    volumes:
     - /dev/null:/var/www/html/index.php
     - ./docker-data/public-files:/var/www/html/files
     - ./docker-data/assets:/var/www/html/assets
     - ./compose/production/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - mapasculturais
    links:
      - mapasculturais


  mapasculturais:
    env_file:
      - mapasculturais.prod.env
    build:
      context: ./
      dockerfile: compose/production/Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/private-files
      - ./docker-data/saas-files:/var/www/SaaS

      # overrides
      - ./compose/overrides/plugins/AldirBlancDataprev/Plugin.php:/var/www/html/protected/application/plugins/AldirBlancDataprev/Plugin.php
      - ./compose/overrides/plugins/AldirBlancDataprev/config-csv-inciso1.php:/var/www/html/protected/application/plugins/AldirBlancDataprev/config-csv-inciso1.php
      - ./compose/overrides/plugins/AldirBlancValidador/Controller.php:/var/www/html/protected/application/plugins/AldirBlancValidador/Controller.php
      - ./compose/overrides/plugins/AldirBlancValidador/Plugin.php:/var/www/html/protected/application/plugins/AldirBlancValidador/Plugin.php
      - ./compose/overrides/plugins/FinancialValidador/Plugin.php:/var/www/html/protected/application/plugins/FinancialValidador/Plugin.php
      - ./compose/overrides/mapas/conf/registrations.php:/var/www/html/protected/application/conf/conf-base.d/registrations.php
      - ./compose/overrides/mapas/conf/notification-types.php:/var/www/html/protected/application/conf/notification-types.php
      - ./compose/overrides/mapas/conf/taxonomies.php:/var/www/html/protected/application/conf/taxonomies.php
      - ./compose/overrides/mapas/lib/EntityAgentRelation.php:/var/www/html/protected/application/lib/MapasCulturais/Traits/EntityAgentRelation.php
      - ./compose/overrides/mapas/modules/CompliantSuggestion/ng.modules.compliantSuggestion.js:/var/www/html/protected/application/lib/modules/CompliantSuggestion/assets/js/ng.modules.compliantSuggestion.js
      - ./compose/overrides/mapas/modules/ProfileCompletion/profile-complete-message.php:/var/www/html/protected/application/lib/modules/ProfileCompletion/layouts/parts/profile-complete-message.php
      - ./compose/overrides/mapas/modules/Reports/registrationsDraftVsSent.php:/var/www/html/protected/application/lib/modules/Reports/layouts/parts/registrationsDraftVsSent.php
      - ./compose/overrides/mapas/BaseV1/downloads.php:/protected/application/themes/BaseV1/layouts/parts/downloads.php
      - ./compose/overrides/mapas/BaseV1/gallery.php:/protected/application/themes/BaseV1/layouts/parts/gallery.php
      - ./compose/overrides/mapas/BaseV1/link-list.php:/protected/application/themes/BaseV1/layouts/parts/link-list.php
      - ./compose/overrides/mapas/BaseV1/report-evaluations.php:/protected/application/themes/BaseV1/views/opportunity/report-evaluations.php
      - ./overrides/mapas/Subsite/_variables.scssprotected/application/themes/Subsite/assets/css/sass/_overrides.scss:/protected/application/themes/Subsite/assets/css/sass/_overrides.scss
    links:
      - db
      - redis
    environment:
      - LOG_LEVEL=DEBUG
      - LOG_ENABLED=true
      
      - APP_MODE=production
      - APP_LCODE=pt_BR
      
      - REDIS_CACHE=redis
      # - SESSIONS_SAVE_PATH=tcp://redis:6379
      - PENDING_PCACHE_RECREATION_INTERVAL=2

      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    depends_on:
      - db
      - redis

  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru
    
      
  db:
    image: mdillon/postgis:11
    restart: always
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
      - POSTGRES_DB_TEST=mapasculturais_test
#    ports:
#      - "5432:5432"
    volumes:
      - ./../dumps/PE/data.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./docker-data/db-data:/var/lib/postgresql/data
