version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
     - /dev/null:/var/www/html/index.php

     - ./docker-data/public-files:/var/www/html/files
     - ./docker-data/assets:/var/www/html/assets

     - ./compose/production/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
    depends_on:
      - mapasculturais
    links:
      - mapasculturais

  mapasculturais:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: compose/production/Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/private-files
      - ./docker-data/saas-files:/var/www/SaaS
      - ./compose/teste.php:/var/www/html/teste.php

    links:
      - redis
    environment:
      - LOG_LEVEL=DEBUG
      - LOG_ENABLED=true
      
      - APP_MODE=production
      - APP_LCODE=pt_BR
      
      - REDIS_CACHE=redis
      - SESSIONS_SAVE_PATH=tcp://sessions:6379
      - PENDING_PCACHE_RECREATION_INTERVAL=2

    depends_on:
      - redis

  sessions:
    image: redis:6
    restart: unless-stopped
    command: --maxmemory 384Mb --maxmemory-policy allkeys-lru
    volumes:
      - ./docker-data/sessions:/data

  redis:
    image: redis:6
    restart: unless-stopped
    command: --maxmemory 384Mb --maxmemory-policy allkeys-lru
   

  metabase:
    image: metabase/metabase
    environment:
      - MB_DB_TYPE=postgres 
      - MB_DB_DBNAME=metabase 
      - MB_DB_PORT=5432 
      - MB_DB_USER=metabase 
      - MB_DB_PASS=metabase 
      - MB_DB_HOST=db_metabase 
    ports:
      - "3000:3000"
    volumes:
      - ../docker-data/metabase:/metabase-data
    depends_on:
      - db_metabase
      
  db_metabase:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_DB=metabase
    volumes:
      - ../compose/metabase.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
      - ../docker-data/metabase-data:/var/lib/postgresql/data
