version: '2'
services:
  mapas:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      
    command: /var/www/dev/start.sh

    ports:
      - "80:80"
    
    volumes:
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/var/private-files
      - ./docker-data/logs:/var/www/var/logs

      - ../docker/common/config.d:/var/www/config/common.d
      - ./config.d:/var/www/config/local.d

      # themes and plugins
      - ../themes/MapasPE:/var/www/src/themes/MapasPE
      - ../plugins/MultipleLocalAuth:/var/www/src/plugins/MultipleLocalAuth
      - ../themes/MapasMuseus:/var/www/src/themes/MapasMuseus
      - ../plugins/MapasBlame:/var/www/src/plugins/MapasBlame
      - ../plugins/SettingsPe:/var/www/src/plugins/SettingsPe
      - ../plugins/AdminLoginAsUser:/var/www/src/plugins/AdminLoginAsUser
      - ../plugins/RegistrationPayments:/var/www/src/plugins/RegistrationPayments
      - ../plugins/Metabase:/var/www/src/plugins/Metabase
      - ../plugins/Accessibility:/var/www/src/plugins/Accessibility
      - ../em-breve:/var/www/html/em-breve
      
      - ../docker/common/conf-base-museus.php:/var/www/src/themes/MapasMuseus/conf-base.php

    environment:
      - PENDING_PCACHE_RECREATION_INTERVAL=10
      - JOBS_INTERVAL=10
      - REDIS_CACHE=redis
      - APP_MODE=development
      - BUILD_ASSETS=1
      - SESSIONS_SAVE_PATH=tcp://redis:6379
      - MAILER_TRANSPORT=smtp://mailhog:1025
      - MAILER_FROM=sysadmin@localhost

    depends_on:
      - db
      - redis
      - mailhog
  
    stdin_open: true
    tty: true


  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru

  db:
    image: postgis/postgis:14-master
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../docker/db:/docker-entrypoint-initdb.d
      - ./docker-data/db-data:/var/lib/postgresql/data

  mailhog: 
    image: mailhog/mailhog
    ports:
      - "8025:8025"
