name: ci

on:
  push:
    tags:
      - "v*.*.*"
    branches:
    - "master"
    - "develop"
    - "basev2"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Invalidate Docker cache
        run: |
          # Use a unique cache key to force cache invalidation
          echo "::set-env name=CACHE_KEY::$(date)"
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/hacklab/mapas-pe 
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./docker/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          CACHE_KEY: ${{ env.CACHE_KEY }}
