version: '2'
services:
  mapas:
    build:
      context: ../
      dockerfile: compose/local/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/private-files

      - ../compose/common/config.d:/var/www/html/protected/application/conf/conf-common.d
      - ../compose/local/config.d:/var/www/html/protected/application/conf/config.d
      - ../compose/common/config.php:/var/www/html/protected/application/conf/config.php
  
      # themes and plugins
      - ../themes/SamplePlugin:/var/www/html/protected/application/themes/SamplePlugin
      - ../themes/Museus:/var/www/html/protected/application/themes/Museus
      - ../plugins/SamplePlugin:/var/www/html/protected/application/plugins/SamplePlugin
      - ../plugins/MultipleLocalAuth:/var/www/html/protected/application/plugins/MultipleLocalAuth
      - ../plugins/MapasBlame:/var/www/html/protected/application/plugins/MapasBlame
      - ../plugins/AldirBlanc:/var/www/html/protected/application/plugins/AldirBlanc
      - ../plugins/AldirBlancDataprev:/var/www/html/protected/application/plugins/AldirBlancDataprev
      - ../plugins/AbstractValidator:/var/www/html/protected/application/plugins/AbstractValidator
      - ../plugins/AldirBlancValidador:/var/www/html/protected/application/plugins/AldirBlancValidador
      - ../plugins/FormCommunication:/var/www/html/protected/application/plugins/FormCommunication
      - ../plugins/GenericValidator:/var/www/html/protected/application/plugins/GenericValidator
      - ../plugins/FinancialValidador:/var/www/html/protected/application/plugins/FinancialValidador
      - ../plugins/SubsiteImporter:/var/www/html/protected/application/plugins/SubsiteImporter
      - ../plugins/SettingsPe:/var/www/html/protected/application/plugins/SettingsPe
      - ../plugins/CadUnico:/var/www/html/protected/application/plugins/CadUnico



      # overrides
      - ../compose/overrides/plugins/AldirBlancDataprev/Plugin.php:/var/www/html/protected/application/plugins/AldirBlancDataprev/Plugin.php
      - ../compose/overrides/plugins/AldirBlancDataprev/config-csv-inciso1.php:/var/www/html/protected/application/plugins/AldirBlancDataprev/config-csv-inciso1.php
      - ../compose/overrides/plugins/AldirBlancValidador/Controller.php:/var/www/html/protected/application/plugins/AldirBlancValidador/Controller.php
      - ../compose/overrides/plugins/AldirBlancValidador/Plugin.php:/var/www/html/protected/application/plugins/AldirBlancValidador/Plugin.php
      - ../compose/overrides/plugins/FinancialValidador/Plugin.php:/var/www/html/protected/application/plugins/FinancialValidador/Plugin.php
      - ../compose/overrides/mapas/conf/registrations.php:/var/www/html/protected/application/conf/conf-base.d/registrations.php
      - ../compose/overrides/mapas/conf/notification-types.php:/var/www/html/protected/application/conf/notification-types.php
      - ../compose/overrides/mapas/conf/taxonomies.php:/var/www/html/protected/application/conf/taxonomies.php
      - ../compose/overrides/mapas/lib/EntityAgentRelation.php:/var/www/html/protected/application/lib/MapasCulturais/Traits/EntityAgentRelation.php
      - ../compose/overrides/mapas/modules/CompliantSuggestion/ng.modules.compliantSuggestion.js:/var/www/html/protected/application/lib/modules/CompliantSuggestion/assets/js/ng.modules.compliantSuggestion.js
      - ../compose/overrides/mapas/modules/ProfileCompletion/profile-complete-message.php:/var/www/html/protected/application/lib/modules/ProfileCompletion/layouts/parts/profile-complete-message.php
      - ../compose/overrides/mapas/modules/Reports/registrationsDraftVsSent.php:/var/www/html/protected/application/lib/modules/Reports/layouts/parts/registrationsDraftVsSent.php
      - ../compose/overrides/mapas/BaseV1/downloads.php:/protected/application/themes/BaseV1/layouts/parts/downloads.php
      - ../compose/overrides/mapas/BaseV1/gallery.php:/protected/application/themes/BaseV1/layouts/parts/gallery.php
      - ../compose/overrides/mapas/BaseV1/link-list.php:/protected/application/themes/BaseV1/layouts/parts/link-list.php
      - ../compose/overrides/mapas/BaseV1/report-evaluations.php:/protected/application/themes/BaseV1/views/opportunity/report-evaluations.php
      - ../compose/overrides/mapas/Subsite/_variables.scss:/protected/application/themes/Subsite/assets/css/sass/_variables.scss
    environment:
      - PENDING_PCACHE_RECREATION_INTERVAL=10
      - JOBS_INTERVAL=10
      - REDIS_CACHE=redis
      - APP_MODE=development

    depends_on:
      - db
      - redis
  
    stdin_open: true
    tty: true


  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru

  db:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../compose/local/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: