version: '2'
services:
  mapas:
    build:
      context: ../
      dockerfile: compose/local/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/private-files

      - ../compose/common/config.d:/var/www/html/protected/application/conf/conf-common.d
      - ../compose/local/config.d:/var/www/html/protected/application/conf/config.d
      - ../compose/common/config.php:/var/www/html/protected/application/conf/config.php
      - ../compose/common/lgpd-terms:/var/www/html/protected/application/conf/lgpd-terms

      # themes and plugins
      - ../themes/Museus:/var/www/html/protected/application/themes/Museus
      - ../plugins/ValuersManagement:/var/www/html/protected/application/plugins/ValuersManagement
      - ../plugins/MultipleLocalAuth:/var/www/html/protected/application/plugins/MultipleLocalAuth
      - ../plugins/MapasBlame:/var/www/html/protected/application/plugins/MapasBlame
      - ../plugins/SubsiteMuseusSwitcher:/var/www/html/protected/application/plugins/SubsiteMuseusSwitcher
      - ../plugins/AldirBlanc:/var/www/html/protected/application/plugins/AldirBlanc
      - ../plugins/AldirBlancDataprev:/var/www/html/protected/application/plugins/AldirBlancDataprev
      - ../plugins/AbstractValidator:/var/www/html/protected/application/plugins/AbstractValidator
      - ../plugins/AldirBlancValidador:/var/www/html/protected/application/plugins/AldirBlancValidador
      - ../plugins/FormCommunication:/var/www/html/protected/application/plugins/FormCommunication
      - ../plugins/GenericValidator:/var/www/html/protected/application/plugins/GenericValidator
      - ../plugins/FinancialValidador:/var/www/html/protected/application/plugins/FinancialValidador
      - ../plugins/SubsiteImporter:/var/www/html/protected/application/plugins/SubsiteImporter
      - ../plugins/Analytics:/var/www/html/protected/application/plugins/Analytics
      - ../plugins/SettingsPe:/var/www/html/protected/application/plugins/SettingsPe
      - ../plugins/CadUnico:/var/www/html/protected/application/plugins/CadUnico
      - ../plugins/ClaimForm:/var/www/html/protected/application/plugins/ClaimForm



      # overrides
      - ../compose/overrides/plugins/AldirBlancDataprev/config-csv-inciso1.php:/var/www/html/protected/application/plugins/AldirBlancDataprev/config-csv-inciso1.php
      - ../compose/overrides/mapas/BaseV1/downloads.php:/protected/application/themes/BaseV1/layouts/parts/downloads.php
      - ../compose/overrides/mapas/BaseV1/gallery.php:/protected/application/themes/BaseV1/layouts/parts/gallery.php
      - ../compose/overrides/mapas/BaseV1/link-list.php:/protected/application/themes/BaseV1/layouts/parts/link-list.php
    environment:
      - PENDING_PCACHE_RECREATION_INTERVAL=10
      - JOBS_INTERVAL=10
      - REDIS_CACHE=redis
      - APP_MODE=development

    depends_on:
      - db
      - redis
  
    stdin_open: true
    tty: true


  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru

  db:
    image: postgis/postgis:14-master
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../compose/db:/docker-entrypoint-initdb.d
      - ../docker-data/db-data:/var/lib/postgresql/data